# Generated by Django 5.2.10 on 2026-01-29 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_encrypted', models.TextField()),
                ('last_name_encrypted', models.TextField()),
                ('date_of_birth_encrypted', models.TextField()),
                ('gender_encrypted', models.TextField()),
                ('allergies_encrypted', models.TextField(null=True)),
                ('medical_record_number_encrypted', models.TextField()),
                ('hashed_medical_record_number', models.CharField(db_index=True, unique=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'Patient',
                'indexes': [models.Index(fields=['hashed_medical_record_number'], name='Patient_hashed__9a2e86_idx'), models.Index(fields=['is_active'], name='Patient_is_acti_f3fde7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_datetime', models.DateTimeField(db_index=True)),
                ('chief_complaint', models.TextField()),
                ('diagnosis', models.TextField()),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('body_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('oxygen', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_encounter_by_user', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_encounters', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_encounter_by_user', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_encounters', to='core.patient')),
            ],
            options={
                'db_table': 'Encounter',
                'indexes': [models.Index(fields=['patient', 'visit_datetime'], name='Encounter_patient_adc581_idx'), models.Index(fields=['doctor', 'visit_datetime'], name='Encounter_doctor__cf971c_idx'), models.Index(fields=['visit_datetime'], name='Encounter_visit_d_cf4633_idx')],
            },
        ),
    ]
