# Generated by Django 5.2.10 on 2026-01-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='patient_enc_patient_38a29a_idx',
            old_name='Encounter_patient_adc581_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='patient_enc_doctor__61b94b_idx',
            old_name='Encounter_doctor__cf971c_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='patient_enc_visit_d_3ee030_idx',
            old_name='Encounter_visit_d_cf4633_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='patient_hashed__be6cd4_idx',
            old_name='Patient_hashed__9a2e86_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='patient_is_acti_9dce51_idx',
            old_name='Patient_is_acti_f3fde7_idx',
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='patient_encounter',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
    ]
