# Generated by Django 5.2.10 on 2026-01-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_encounter_patient_adc581_idx_patient_enc_patient_38a29a_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='patient_app_patient_c36a3b_idx',
            old_name='patient_enc_patient_38a29a_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='patient_app_doctor__b05839_idx',
            old_name='patient_enc_doctor__61b94b_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='patient_app_visit_d_e049e8_idx',
            old_name='patient_enc_visit_d_3ee030_idx',
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='patient_appointments',
        ),
    ]
