# Generated by Django 5.2.10 on 2026-01-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_patient_enc_patient_38a29a_idx_patient_app_patient_c36a3b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='first_name_hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name_hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
