# Generated by Django 5.2.10 on 2026-02-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
