# Generated by Django 5.2.10 on 2026-02-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('medical_record', 'Medical Record'), ('lab_report', 'Lab Report'), ('prescription', 'Prescription'), ('insurance', 'Insurance Document'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
