# Generated by Django 5.2.10 on 2026-02-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('medical_record', 'Medical Record'), ('lab_report', 'Lab Report'), ('prescription', 'Prescription'), ('insurance', 'Insurance Document'), ('consent_form', 'Consent Form'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
