# Generated by Django 5.2.10 on 2026-01-29 11:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_organization_current_member_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20)),
                ('max_members', models.IntegerField(help_text='Maximum number of members allowed. Use -1 for unlimited', validators=[django.core.validators.MinValueValidator(-1)])),
                ('features', models.JSONField(blank=True, default=dict, help_text='JSON object with feature flags and limits')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this plan is publicly available for subscription')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions_plan',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('subscribed', 'Subscribed'), ('renewed', 'Renewed'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended')], max_length=20)),
                ('performed_by_email', models.EmailField(max_length=254)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='organizations.organization')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name_plural': 'Subscription histories',
                'db_table': 'subscriptions_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
