# Generated by Django 5.2.10 on 2026-02-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionhistory_previous_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='trial_days',
        ),
    ]
