# Generated by Django 5.2.10 on 2026-02-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tenant_admin',
            field=models.BooleanField(default=False),
        ),
    ]
