# Generated by Django 5.2.10 on 2026-02-02 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_password_generated_at_user_password_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (e.g., 1234567890).', regex='^\\d{10}$')]),
        ),
    ]
