# Generated by Django 5.2.10 on 2026-02-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_permission_role_rolepermission_role_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.UserRole', to='users.role'),
        ),
    ]
