# Generated by Django 5.2.10 on 2026-02-06 05:42

from django.db import migrations


def create_permissions_and_roles(apps, schema_editor):
    """
    Create initial permissions and roles, and assign to superusers
    """
    Permission = apps.get_model('users', 'Permission')
    Role = apps.get_model('users', 'Role')
    RolePermission = apps.get_model('users', 'RolePermission')
    User = apps.get_model('users', 'User')
    UserRole = apps.get_model('users', 'UserRole')

    # Define permissions to create
    permissions_data = [
        # User permissions
        {'name': 'users.create', 'description': 'Can create users'},
        {'name': 'users.read', 'description': 'Can read/view users'},
        {'name': 'users.update', 'description': 'Can update users'},
        {'name': 'users.delete', 'description': 'Can delete users'},

        # Permission permissions
        {'name': 'permissions.create', 'description': 'Can create permissions'},
        {'name': 'permissions.read', 'description': 'Can read/view permissions'},
        {'name': 'permissions.update', 'description': 'Can update permissions'},
        {'name': 'permissions.delete', 'description': 'Can delete permissions'},

        # Role permissions
        {'name': 'roles.create', 'description': 'Can create roles'},
        {'name': 'roles.read', 'description': 'Can read/view roles'},
        {'name': 'roles.update', 'description': 'Can update roles'},
        {'name': 'roles.delete', 'description': 'Can delete roles'},
    ]

    # Create permissions
    created_permissions = []
    for perm_data in permissions_data:
        permission, created = Permission.objects.get_or_create(
            name=perm_data['name'],
            defaults={
                'description': perm_data['description'],
                'is_active': True,
                'is_deleted': False,
            }
        )
        created_permissions.append(permission)
        if created:
            print(f"Created permission: {permission.name}")

    # Create Admin role with all permissions
    admin_role, created = Role.objects.get_or_create(
        name='superuser',
        defaults={
            'description': 'Full administrative access with all permissions',
            'is_system_role': True,
            'is_active': True,
            'is_deleted': False,
        }
    )

    if created:
        print(f"Created role: {admin_role.name}")

    # Assign all permissions to Admin role
    for permission in created_permissions:
        role_permission, created = RolePermission.objects.get_or_create(
            role=admin_role,
            permission=permission,
            defaults={
                'is_active': True,
                'is_deleted': False,
            }
        )
        if created:
            print(f"Assigned {permission.name} to {admin_role.name}")

    # Assign Admin role to all superusers
    superusers = User.objects.filter(is_superuser=True)
    for superuser in superusers:
        user_role, created = UserRole.objects.get_or_create(
            user=superuser,
            role=admin_role,
            defaults={
                'is_active': True,
                'is_deleted': False,
            }
        )
        if created:
            print(f"Assigned {admin_role.name} role to superuser: {
                  superuser.email}")


def reverse_permissions_and_roles(apps, schema_editor):
    """
    Remove the created permissions and roles
    """
    Permission = apps.get_model('users', 'Permission')
    Role = apps.get_model('users', 'Role')

    # Delete permissions
    permission_names = [
        'users.create', 'users.read', 'users.update', 'users.delete',
        'permissions.create', 'permissions.read', 'permissions.update', 'permissions.delete',
        'roles.create', 'roles.read', 'roles.update', 'roles.delete',
    ]
    Permission.objects.filter(name__in=permission_names).delete()

    # Delete Admin role (cascade will handle RolePermission and UserRole)
    Role.objects.filter(name='superuser').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_roles'),
    ]

    operations = [
        migrations.RunPython(
            create_permissions_and_roles,
            reverse_permissions_and_roles
        ),
    ]
