# Generated by Django 5.2.10 on 2026-02-09 10:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_roles_and_permissions_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles_permission', through='users.RolePermission', to='users.permission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='previous_passwords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), null=True, size=3, unique=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.role'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['name'], name='permissions_name_6a4248_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['is_active', 'is_deleted'], name='permissions_is_acti_a9f514_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='roles_name_a96913_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_active', 'is_deleted'], name='roles_is_acti_2e504d_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_system_role'], name='roles_is_syst_135658_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'is_deleted', 'is_active'], name='role_permis_role_id_49aeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission', 'is_deleted', 'is_active'], name='role_permis_permiss_f4eccc_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'permission', 'is_deleted', 'is_active'], name='role_permis_role_id_1b2698_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_deleted', 'is_active'], name='user_roles_user_id_dfdaba_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'is_deleted', 'is_active'], name='user_roles_role_id_4d166b_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role', 'is_deleted', 'is_active'], name='user_roles_user_id_b3cc7e_idx'),
        ),
    ]
