# Generated by Django 5.2.10 on 2026-02-18 07:25

from django.db import migrations


def create_module_permissions(apps, schema_editor):
    """
    Create permissions for patients, appointments, and documents modules
    """
    if schema_editor.connection.schema_name == 'public':
        return

    Permission = apps.get_model('users', 'Permission')

    permissions_data = [
        # Patient permissions
        {'name': 'patients.create', 'description': 'Can create patients'},
        {'name': 'patients.read', 'description': 'Can read/view patients'},
        {'name': 'patients.update', 'description': 'Can update patients'},
        {'name': 'patients.delete', 'description': 'Can delete patients'},

        # Appointment permissions
        {'name': 'appointments.create', 'description': 'Can create appointments'},
        {'name': 'appointments.read', 'description': 'Can read/view appointments'},
        {'name': 'appointments.update', 'description': 'Can update appointments'},
        {'name': 'appointments.delete', 'description': 'Can delete appointments'},

        # Document permissions
        {'name': 'documents.create', 'description': 'Can create documents'},
        {'name': 'documents.read', 'description': 'Can read/view documents'},
        {'name': 'documents.update', 'description': 'Can update documents'},
        {'name': 'documents.delete', 'description': 'Can delete documents'},
    ]

    for perm_data in permissions_data:
        permission, created = Permission.objects.get_or_create(
            name=perm_data['name'],
            defaults={
                'description': perm_data['description'],
                'is_active': True,
                'is_deleted': False,
            }
        )
        if created:
            print(f"Created permission: {permission.name}")


def reverse_module_permissions(apps, schema_editor):
    """
    Remove permissions for patients, appointments, and documents modules
    """
    Permission = apps.get_model('users', 'Permission')

    permission_names = [
        'patients.create', 'patients.read', 'patients.update', 'patients.delete',
        'appointments.create', 'appointments.read', 'appointments.update', 'appointments.delete',
        'documents.create', 'documents.read', 'documents.update', 'documents.delete',
    ]

    Permission.objects.filter(name__in=permission_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_role_permissions_alter_user_previous_passwords_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_module_permissions,
            reverse_module_permissions,
        ),
    ]
