# Generated by Django 5.2.10 on 2026-01-29 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='domain',
            table='Organization_domains',
        ),
    ]
