# Generated by Django 5.2.10 on 2026-01-29 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_domain_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='domain',
            table='organization_domains',
        ),
    ]
