# Generated by Django 5.2.10 on 2026-01-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_domain_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='current_member_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
