# Generated by Django 5.2.10 on 2026-01-29 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_current_member_count_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
