# Generated by Django 5.2.10 on 2026-01-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='current_member_count',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_trial',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='subscription_start_date',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='trial_end_date',
        ),
    ]
