# Generated by Django 5.2.10 on 2026-02-01 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_organization_current_member_count_and_more'),
        ('subscriptions', '0002_subscriptionhistory_previous_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='max_users',
        ),
        migrations.AddField(
            model_name='organization',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='current_member_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organization',
            name='grace_period_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['subscription_status'], name='organizatio_subscri_72b760_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['subscription_end_date'], name='organizatio_subscri_8a4b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_bdc355_idx'),
        ),
    ]
