# Generated by Django 5.2.10 on 2026-02-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_alter_organization_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_trial',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='trial_end_date',
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], max_length=20),
        ),
    ]
