# Generated by Django 5.2.10 on 2026-02-17 06:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_remove_organization_is_trial_and_more'),
        ('subscriptions', '0003_remove_subscriptionplan_trial_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('transaction_type', models.CharField(choices=[('subscription', 'Subscription Payment'), ('renewal', 'Renewal Payment'), ('upgrade', 'Upgrade Payment'), ('refund', 'Refund')], default='subscription', max_length=20)),
                ('billing_interval', models.CharField(max_length=20)),
                ('processed_by_email', models.EmailField(max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_records', to='subscriptions.subscriptionplan')),
                ('subscription_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_record', to='subscriptions.subscriptionhistory')),
            ],
            options={
                'db_table': 'revenue',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='revenue_created_5b7a3c_idx'), models.Index(fields=['organization', '-created_at'], name='revenue_organiz_268c23_idx'), models.Index(fields=['transaction_type'], name='revenue_transac_b7fdcd_idx')],
            },
        ),
    ]
