# Generated by Django 5.2.10 on 2026-02-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='transaction_type',
            field=models.CharField(choices=[('subscription', 'Subscription Payment'), ('renewal', 'Renewal Payment'), ('upgrade', 'Upgrade Payment')], default='subscription', max_length=20),
        ),
    ]
