# Generated by Django 5.2.10 on 2026-02-10 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('body', models.JSONField(blank=True, default=dict, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status_code', models.IntegerField(db_index=True)),
                ('response_time_ms', models.FloatField(help_text='Response time in milliseconds')),
                ('response_body', models.JSONField(blank=True, default=dict, help_text='Only stored for failed requests (status >= 400)', null=True)),
                ('is_failed', models.BooleanField(db_index=True, default=False, help_text='True if status_code >= 400')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'db_table': 'request_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['-timestamp'], name='request_log_timesta_ca68b4_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['method', 'path'], name='request_log_method_814a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['is_failed', '-timestamp'], name='request_log_is_fail_27cdb0_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['user', '-timestamp'], name='request_log_user_id_02842d_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['status_code'], name='request_log_status__5a9c0b_idx'),
        ),
    ]
